const Hero_Alan_Sasha = [{
    "1": [`Been here before, it's in my muscle memory`, 6],
    "6": [`I'm pretty sure, I recognize you`, 9],
    "9": [`There is somethin' in your eyes`, 11],
    "11": [`Won't let you get away tonight`, 16],
    "16": [`You leave me in the dark`, 19],
    "19": [`I'm stumblin' around like I'm a question mark`, 23],
    "23": [`Wonderin' if you're around to catch me if I fall`, 26],
    "26": [`If I come crash into the wall`, 31],
    "31": [`Will you light me up, jump-start my heart?`, 36],
    "36": [`I need someone before the sun goes down`, 41],
    "41": [`Who's gonna save me now?`, 45],
    "45": [`Some kind of hero`, 48],
    "48": [`I can't breathe, hopin' you're here to rescue me`, 53],
    "53": [`Before the sun goes down`, 56],
    "56": [`Who's gonna save me now?`, 60],
    "60": [`Some kind of hero`, 63],
    "63": [`♪`, 78],
    "78": [`Been here before, it's in my muscle memory`, 82],
    "82": [`I'm pretty sure, I've felt this energy`, 86],
    "86": [`There's somethin' in your touch`, 88],
    "88": [`Somethin' reminded me of us`, 92],
    "92": [`Will you light me up, jump-start my heart?`, 97],
    "97": [`I need someone before the sun goes down`, 102],
    "102": [`Who's gonna save me now?`, 106],
    "106": [`Some kind of hero`, 108],
    "108": [`I can't breathe, hopin' you're here to rescue me`, 114],
    "114": [`Before the sun goes down`, 118],
    "118": [`Who's gonna save me now?`, 121],
    "121": [`Some kind of hero`, 124],
    "124": [`♪`, 137],
    "137": [`Some kind of hero`, 139],
    "139": [`♪`, 0],
}]

const Let_It_Go_Idina_Frozen = [{
    "0": [`♪`, 0],
    "13": [`The snow glows white on the mountain tonight`, 17],
    "17": [`Not a footprint to be seen`, 21],
    "21": [`A kingdom of isolation`, 24],
    "24": [`And it looks like I'm the queen`, 28],
    "28": [`The wind is howling like this swirling storm inside`, 35],
    "35": [`Couldn't keep it in, heaven knows I tried`, 42],
    "42": [`Don't let them in`, 44],
    "44": [`Don't let them see`, 46],
    "46": [`Be the good girl you always have to be`, 49],
    "49": [`Conceal, don't feel`, 51],
    "51": [`Don't let them know`, 55],
    "55": [`Well, now they know`, 59],
    "59": [`Let it go!`, 60],
    "60": [`Let it go!`, 62],
    "62": [`Can't hold it back anymore`, 66],
    "66": [`Let it go!`, 67],
    "66": [`Let it go!`, 70],
    "70": [`Turn away and slam the door`, 73],
    "73": [`I don't care`, 76],
    "76": [`What they're going to say`, 80],
    "80": [`Let the storm rage on`, 83],
    "83": [`The cold never bothered me anyway`, 87],
    "87": [`♪`, 91],
    "91": [`It's funny how some distance`, 94],
    "94": [`Makes everything seem small`, 98],
    "98": [`And the fears that once controlled me`, 100],
    "101": [`Can't get to me at all`, 105],
    "105": [`It's time to see what I can do`, 109],
    "109": [`To test the limits and break through`, 112],
    "112": [`No right, no wrong, no rules for me`, 117],
    "117": [`I'm free`, 120],
    "120": [`Let it go!`, 122],
    "122": [`Let it go!`, 124],
    "124": [`I am one with the wind and sky`, 127],
    "127": [`Let it go!`, 128],
    "128": [`Let it go!`, 130],
    "131": [`You'll never see me cry`, 135],
    "135": [`Here I stand and here I'll stay`, 141],
    "141": [`Let the storm rage on`, 145],
    "145": [`♪`, 153],
    "153": [`My power flurries through the air into the ground`, 160],
    "160": [`My soul is spiraling in frozen fractals all around`, 167],
    "167": [`And one thought crystallizes like an icy blast`, 174],
    "174": [`I'm never going back, The past is in the past`, 181],
    "182": [`Let it go!`, 183],
    "183": [`Let it go!`, 185],
    "185": [`And I'll rise like the break of dawn`, 189],
    "189": [`Let it go!`, 190],
    "190": [`Let it go!`, 192],
    "193": [`That perfect girl is gone`, 196],
    "196": [`Here I stand in the light of day`, 204],
    "205": [`Let the storm rage on!`, 211],
    "211": [`The cold never bothered me anyway`, 218],
    "218": [`♪`, 0],
}]