let podcasts = [
    {
        title: "Unstoppable",
        path: "assets\\sounds\\Sia - Unstoppable.mp3",
        cover: "assets\\cover\\Unstoppable.jpg",
        creator: "Sia",
        channel: "Sia",
        podcastLength: "",
        integerLength: 0,
    },
    {
        title: "Grew up at midnight",
        path: "assets\\sounds\\Grew Up At Midnight.mp3",
        cover: "assets\\cover\\Grew Up At Midnight.jpg",
        creator: "The Maccabees",
        channel: "The Maccabees",
        podcastLength: "",
        integerLength: 0,
    },
    {
        title: "On my way",
        path: "assets\\sounds\\On My Way.mp3",
        cover: "assets\\cover\\On My Way.jpg",
        creator: "Alan Walker, Sabrina Carpenter & Farruko",
        channel: "Alan Walker",
        podcastLength: "",
        integerLength: 0,
    },
    {
        title: "Good day for dreaming",
        path: "assets\\sounds\\Good Day For Dreaming.mp3",
        cover: "assets\\cover\\Good Day For Dreaming.jpg",
        creator: "Ruelle",
        channel: "Ruelle",
        podcastLength: "",
        integerLength: 0,
    },
];
